[package]
name = "buttplug-lite"
version = "0.4.2"
authors = ["Runtime's Shady Backroom <76618880+runtime-shady-backroom@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.0.0", features = ["full"] }
warp = "~0.3.0" # uses tokio 1.0
futures = { version = "^0.3.0", default-features = false }
buttplug = { version = "^2.1.3", default-features = false, features = ["thread-pool-runtime", "client", "server", "serialize-json", "btleplug-manager", "xinput-manager", "serial-manager", "lovense-dongle-manager"] } # uses tokio 1.1.0
serde = "^1.0.0"
toml = "^0.5.0"
app_dirs = "^1.2.1"
iced = "~0.3.0"
iced_native = "^0.4.0"
lazy_static = "^1.4.0"
